USE Filmy;

DROP TABLE IF EXISTS Obsada;
DROP TABLE IF EXISTS GatunkiFilmu;
DROP TABLE IF EXISTS NagrodyFilmu;
DROP TABLE IF EXISTS FilmyDoObejrzenia;
DROP TABLE IF EXISTS Opinie;
DROP TABLE IF EXISTS Nagrody;
DROP TABLE IF EXISTS Gatunki;
DROP TABLE IF EXISTS Filmy;
DROP TABLE IF EXISTS Rezyserowie;
DROP TABLE IF EXISTS Aktorzy;
DROP TABLE IF EXISTS Krytycy;
DROP TABLE IF EXISTS ZwykliUzytkownicy;
DROP TABLE IF EXISTS Osoby;